# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='subject',
            new_name='job_title',
        ),
    ]
