# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20151229_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationaluniversities',
            name='university_photo',
            field=models.ImageField(upload_to='university_photos'),
        ),
        migrations.AlterField(
            model_name='localuniversities',
            name='university_photo',
            field=models.ImageField(upload_to='university_photos'),
        ),
    ]
