# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20160119_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaluniversities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='internationaluniversities',
            name='university_photo',
        ),
        migrations.RemoveField(
            model_name='localuniversities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='localuniversities',
            name='university_photo',
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='course_five',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='course_four',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='course_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='course_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='course_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='description5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 20, 12, 27, 31, 203879, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='featured',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 27, 46, 860288, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 27, 57, 131305, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 28, 7, 234305, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='po_box',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 28, 18, 908497, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_logo',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 28, 31, 539107, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_motto',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 28, 41, 268541, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_photo1',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 28, 52, 80694, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_photo2',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 29, 3, 82056, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_photo3',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 29, 14, 435357, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_photo4',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 29, 24, 755431, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_photo5',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 29, 35, 885161, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationaluniversities',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='course_five',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='course_four',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='course_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='course_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='course_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='description5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 20, 12, 29, 46, 976159, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='featured',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 29, 59, 7944, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 30, 10, 73941, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 30, 20, 326885, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='po_box',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 30, 30, 232026, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_logo',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 30, 40, 291367, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_motto',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 12, 30, 51, 948138, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_photo1',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 31, 3, 433553, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_photo2',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 31, 18, 773857, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_photo3',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 31, 35, 659153, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_photo4',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 31, 46, 477523, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_photo5',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 12, 31, 59, 198775, tzinfo=utc), upload_to='universities/university_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
