# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20160120_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaluniversities',
            name='university_file',
            field=models.FileField(blank=True, upload_to='universities/university_files'),
        ),
        migrations.AddField(
            model_name='localuniversities',
            name='university_file',
            field=models.FileField(blank=True, upload_to='universities/university_files'),
        ),
    ]
