# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20160126_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localuniversities',
            old_name='university_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='localuniversities',
            old_name='university_photo1',
            new_name='photo1',
        ),
    ]
