# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_five',
            new_name='h2_sub_heading_four',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_four',
            new_name='h2_sub_heading_one',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_six',
            new_name='h2_sub_heading_three',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_three',
            new_name='h2_sub_heading_two',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sub_heading_two',
            new_name='h3_sub_heading_four',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_five',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_six',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_three',
        ),
        migrations.AddField(
            model_name='article',
            name='h3_sub_heading_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h3_sub_heading_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h3_sub_heading_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h4_sub_heading_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h4_sub_heading_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h4_sub_heading_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h4_sub_heading_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h5_sub_heading_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h5_sub_heading_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h5_sub_heading_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h5_sub_heading_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h6_sub_heading_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h6_sub_heading_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h6_sub_heading_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='h6_sub_heading_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
