# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('excellence_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellenceabout',
            name='page',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 12, 34, 29, 741862, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
