# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kazi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description1', models.TextField(verbose_name='Job Description')),
                ('job_description2', models.TextField(blank=True, verbose_name='Paragraph Two(Optional)')),
                ('job_description3', models.TextField(blank=True, verbose_name='Paragraph Three(Optional)')),
                ('job_description4', models.TextField(blank=True, verbose_name='Paragraph Four(Optional)')),
                ('job_description5', models.TextField(blank=True, verbose_name='Paragraph Five(Optional)')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
