# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_one', models.TextField()),
                ('heading_two', models.CharField(max_length=500)),
                ('text_two', models.TextField()),
                ('heading_one', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('image_one', models.ImageField(upload_to='')),
                ('file_five', models.FileField(upload_to='')),
            ],
        ),
    ]
