# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160110_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 10, 21, 49, 53, 519187, tzinfo=utc), verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
