# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='file_four',
            field=models.FileField(default=datetime.datetime(2016, 1, 11, 14, 56, 31, 354666, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='file_one',
            field=models.FileField(default=datetime.datetime(2016, 1, 11, 14, 56, 46, 207547, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='file_three',
            field=models.FileField(default=datetime.datetime(2016, 1, 11, 14, 56, 58, 209519, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='file_two',
            field=models.FileField(default=datetime.datetime(2016, 1, 11, 14, 57, 11, 796855, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
