# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file_five',
            field=models.FileField(upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_four',
            field=models.FileField(upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_one',
            field=models.FileField(upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_three',
            field=models.FileField(upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_two',
            field=models.FileField(upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_five',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_four',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_one',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_three',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_two',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
    ]
