# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160119_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='text_five',
            new_name='h1_paragraph1',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text_four',
            new_name='h2_paragraph1',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text_one',
            new_name='h3_paragraph1',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text_three',
            new_name='h4_paragraph1',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='text_two',
            new_name='h5_paragraph1',
        ),
        migrations.AddField(
            model_name='new',
            name='h1_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h1_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h4_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h4_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h5_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h5_paragraph3',
            field=models.TextField(blank=True),
        ),
    ]
