# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20160121_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file_five',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_one',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_three',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file_two',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='news/news_photos'),
        ),
    ]
