# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160121_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file_four',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_four',
            field=models.ImageField(upload_to='news/news_photos'),
        ),
    ]
