# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160121_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='file_six',
            field=models.FileField(blank=True, upload_to='news/news_files'),
        ),
        migrations.AddField(
            model_name='new',
            name='h6_paragraph1',
            field=models.TextField(default=datetime.datetime(2016, 1, 21, 11, 59, 38, 739505, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='h6_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h6_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='heading_six',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 11, 59, 48, 887449, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='image_six',
            field=models.ImageField(default=datetime.datetime(2016, 1, 21, 12, 0, 0, 313923, tzinfo=utc), upload_to='news/news_photos'),
            preserve_default=False,
        ),
    ]
