# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.CharField(max_length=500)),
                ('high_school_name', models.CharField(max_length=500)),
                ('high_school_logo', models.ImageField(upload_to='high_school/high_school_photos')),
                ('high_school_motto', models.CharField(max_length=500)),
                ('high_school_photo1', models.ImageField(upload_to='high_school/high_school_photos')),
                ('text_one', models.TextField(blank=True)),
                ('high_school_photo2', models.ImageField(upload_to='high_school/high_school_photos')),
                ('text_two', models.TextField(blank=True)),
                ('high_school_photo3', models.ImageField(upload_to='high_school/high_school_photos')),
                ('text_three', models.TextField(blank=True)),
                ('high_school_photo4', models.ImageField(upload_to='high_school/high_school_photos')),
                ('text_four', models.TextField(blank=True)),
                ('high_school_photo5', models.ImageField(upload_to='high_school/high_school_photos')),
                ('text_five', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('po_box', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('suject_one', models.CharField(blank=True, max_length=500)),
                ('suject_two', models.CharField(blank=True, max_length=500)),
                ('suject_three', models.CharField(blank=True, max_length=500)),
                ('suject_four', models.CharField(blank=True, max_length=500)),
                ('suject_five', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
