# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='text_five',
            new_name='descrition1',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='text_four',
            new_name='descrition2',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='text_one',
            new_name='descrition3',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='text_three',
            new_name='descrition4',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='text_two',
            new_name='descrition5',
        ),
    ]
