# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('high_school_photo', models.ImageField(upload_to='school_photos')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
