# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0002_auto_20160119_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='descrition1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='descrition2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='descrition3',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='descrition4',
            new_name='description4',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='descrition5',
            new_name='description5',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='suject_five',
            new_name='sujbect_five',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='suject_four',
            new_name='sujbect_four',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='suject_one',
            new_name='sujbect_one',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='suject_three',
            new_name='sujbect_three',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='suject_two',
            new_name='sujbect_two',
        ),
    ]
