# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0002_auto_20151229_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='featured',
            field=models.CharField(default=datetime.datetime(2016, 1, 11, 15, 37, 1, 225020, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
