# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0003_highschool_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='high_school_photo',
        ),
        migrations.AddField(
            model_name='highschool',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='description5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 16, 12, 22, 9, 346003, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_logo',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_photo1',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_photo2',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_photo3',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_photo4',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='high_school_photo5',
            field=models.ImageField(blank=True, upload_to='school_photos'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 1, 16, 12, 22, 25, 206346, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschool',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 1, 16, 12, 22, 41, 168299, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschool',
            name='po_box',
            field=models.CharField(default=datetime.datetime(2016, 1, 16, 12, 22, 55, 807303, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highschool',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
