# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0003_auto_20160119_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='sujbect_five',
            new_name='subject_five',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='sujbect_four',
            new_name='subject_four',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='sujbect_one',
            new_name='subject_one',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='sujbect_three',
            new_name='subject_three',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='sujbect_two',
            new_name='subject_two',
        ),
    ]
