# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0004_auto_20160119_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='high_school_file',
            field=models.FileField(blank=True, upload_to='high_school/high_school_files'),
        ),
    ]
