# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0004_auto_20160116_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='high_school_motto',
            field=models.CharField(default=datetime.datetime(2016, 1, 16, 12, 31, 55, 392471, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
