# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_schools', '0005_highschool_high_school_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='suject_five',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='highschool',
            name='suject_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='highschool',
            name='suject_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='highschool',
            name='suject_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='highschool',
            name='suject_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
