from django.db import models

# Create your models here.


class Article(models.Model):
    heading_one = models.CharField(max_length=500)
    question = models.CharField(max_length=200)
    h1_paragraph_one = models.TextField()
    h1_paragraph_two = models.TextField(blank=True)
    h1_paragraph_three = models.TextField(blank=True)
    answer = models.CharField(max_length=200)
    h1_paragraph_four = models.TextField()
    h1_paragraph_five = models.TextField(blank=True)
    h1_paragraph_six = models.TextField(blank=True)
    h1_paragraph_seven = models.TextField(blank=True)
    h1_paragraph_eight = models.TextField(blank=True)
    h1_paragraph_nine = models.TextField(blank=True)
    h1_paragraph_ten = models.TextField(blank=True)
    image_one = models.ImageField(upload_to='magazine_photos') 

    heading_two = models.CharField(max_length=500)
    h2_sub_heading_one = models.CharField(max_length=200, blank=True)
    h2_paragraph_one = models.TextField(blank=True)
    h2_paragraph_two = models.TextField(blank=True)
    h2_paragraph_three = models.TextField(blank=True)
    h2_sub_heading_two = models.CharField(max_length=200, blank=True)
    h2_paragraph_four = models.TextField(blank=True)
    h2_paragraph_five = models.TextField(blank=True)
    h2_paragraph_six = models.TextField(blank=True)
    h2_sub_heading_three = models.CharField(max_length=200, blank=True)
    h2_paragraph_seven = models.TextField(blank=True)
    h2_paragraph_eight = models.TextField(blank=True)
    h2_paragraph_nine = models.TextField(blank=True)
    h2_sub_heading_four = models.CharField(max_length=200, blank=True)
    h2_paragraph_ten = models.TextField(blank=True)
    h2_paragraph_eleven = models.TextField(blank=True)
    h2_paragraph_twelve = models.TextField(blank=True)
    image_two = models.ImageField(upload_to='magazine_photos') 

    heading_three = models.CharField(max_length=500)
    h3_sub_heading_one = models.CharField(max_length=200, blank=True)
    h3_paragraph_one = models.TextField(blank=True)
    h3_paragraph_two = models.TextField(blank=True)
    h3_paragraph_three = models.TextField(blank=True)
    h3_sub_heading_two = models.CharField(max_length=200, blank=True)
    h3_paragraph_four = models.TextField(blank=True)
    h3_paragraph_five = models.TextField(blank=True)
    h3_paragraph_six = models.TextField(blank=True)
    h3_sub_heading_three = models.CharField(max_length=200, blank=True)
    h3_paragraph_seven = models.TextField(blank=True)
    h3_paragraph_eight = models.TextField(blank=True)
    h3_paragraph_nine = models.TextField(blank=True)
    h3_sub_heading_four = models.CharField(max_length=200, blank=True)
    h3_paragraph_ten = models.TextField(blank=True)
    h3_paragraph_eleven = models.TextField(blank=True)
    h3_paragraph_twelve = models.TextField(blank=True)
    image_three = models.ImageField(upload_to='magazine_photos') 

    heading_four = models.CharField(max_length=500)
    h4_sub_heading_one = models.CharField(max_length=200, blank=True)
    h4_paragraph_one = models.TextField(blank=True)
    h4_paragraph_two = models.TextField(blank=True)
    h4_paragraph_three = models.TextField(blank=True)
    h4_sub_heading_two = models.CharField(max_length=200, blank=True)
    h4_paragraph_four = models.TextField(blank=True)
    h4_paragraph_five = models.TextField(blank=True)
    h4_paragraph_six = models.TextField(blank=True)
    h4_sub_heading_three = models.CharField(max_length=200, blank=True)
    h4_paragraph_seven = models.TextField(blank=True)
    h4_paragraph_eight = models.TextField(blank=True)
    h4_paragraph_nine = models.TextField(blank=True)
    h4_sub_heading_four = models.CharField(max_length=200, blank=True)
    h4_paragraph_ten = models.TextField(blank=True)
    h4_paragraph_eleven = models.TextField(blank=True)
    h4_paragraph_twelve = models.TextField(blank=True)
    image_four = models.ImageField(upload_to='magazine_photos') 

    heading_five = models.CharField(max_length=500)
    h5_sub_heading_one = models.CharField(max_length=200, blank=True)
    h5_paragraph_one = models.TextField(blank=True)
    h5_paragraph_two = models.TextField(blank=True)
    h5_paragraph_three = models.TextField(blank=True)
    h5_sub_heading_two = models.CharField(max_length=200, blank=True)
    h5_paragraph_four = models.TextField(blank=True)
    h5_paragraph_five = models.TextField(blank=True)
    h5_paragraph_six = models.TextField(blank=True)
    h5_sub_heading_three = models.CharField(max_length=200, blank=True)
    h5_paragraph_seven = models.TextField(blank=True)
    h5_paragraph_eight = models.TextField(blank=True)
    h5_paragraph_nine = models.TextField(blank=True)
    h5_sub_heading_four = models.CharField(max_length=200, blank=True)
    h5_paragraph_ten = models.TextField(blank=True)
    h5_paragraph_eleven = models.TextField(blank=True)
    h5_paragraph_twelve = models.TextField(blank=True)
    image_five = models.ImageField(upload_to='magazine_photos') 

    heading_six = models.CharField(max_length=500)
    h6_sub_heading_one = models.CharField(max_length=200, blank=True)
    h6_paragraph_one = models.TextField(blank=True)
    h6_paragraph_two = models.TextField(blank=True)
    h6_paragraph_three = models.TextField(blank=True)
    h6_sub_heading_two = models.CharField(max_length=200, blank=True)
    h6_paragraph_four = models.TextField(blank=True)
    h6_paragraph_five = models.TextField(blank=True)
    h6_paragraph_six = models.TextField(blank=True)
    h6_sub_heading_three = models.CharField(max_length=200, blank=True)
    h6_paragraph_seven = models.TextField(blank=True)
    h6_paragraph_eight = models.TextField(blank=True)
    h6_paragraph_nine = models.TextField(blank=True)
    h6_sub_heading_four = models.CharField(max_length=200, blank=True)
    h6_paragraph_ten = models.TextField(blank=True)
    h6_paragraph_eleven = models.TextField(blank=True)
    h6_paragraph_twelve = models.TextField(blank=True)
    image_six = models.ImageField(upload_to='magazine_photos') 
    pub_date = models.DateTimeField('Date Published', auto_now_add=True, auto_now=False)

    def __str__(self):
        return str(self.pub_date)
