# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160404_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Career  Option(Student Only)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Career Option(Student Only)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Third Career Option(Student Only)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Level(Student Only)'),
        ),
    ]
