# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_email',
        ),
    ]
