# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160404_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Your Phone Number'),
        ),
    ]
