# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160404_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Status'),
        ),
    ]
