# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject One')),
                ('subject1_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject One Code')),
                ('subject2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Two')),
                ('subject2_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject  Two Code')),
                ('subject3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Three')),
                ('subject3_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Three Code')),
                ('subject4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Four')),
                ('subject4_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Four Code')),
                ('subject5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Five')),
                ('subject5_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Five Code')),
                ('subject6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Six')),
                ('subject6_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Six Code')),
                ('subject7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Seven')),
                ('subject7_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Seven Code')),
                ('subject8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Eight')),
                ('subject8_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Eight Code')),
                ('subject9', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Nine')),
                ('subject9_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Nine Code')),
                ('subject10', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Ten')),
                ('subject10_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Ten Code')),
                ('subject11', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Eleven')),
                ('subject11_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Eleven Code')),
                ('subject12', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Twelve')),
                ('subject12_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Twelve Code')),
                ('subject13', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Thirteen')),
                ('subject13_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Thirteen Code')),
                ('subject14', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Fourteen')),
                ('subject14_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Fourteen Code')),
                ('subject15', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Fifteen')),
                ('subject15_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Fifteen  Code')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip One')),
                ('tip2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Two')),
                ('tip3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Three')),
                ('tip4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Four')),
                ('tip5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Five')),
                ('tip6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Six')),
                ('tip7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Seven')),
                ('tip8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eight')),
                ('tip9', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Nine')),
                ('tip10', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Ten')),
                ('tip11', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eleven')),
                ('tip12', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Twelve')),
                ('tip13', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Thirteen')),
                ('tip14', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fourteen')),
                ('tip15', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fifteen')),
            ],
        ),
    ]
