# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20160405_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicFormOne',
            new_name='BasicForm1Exam',
        ),
    ]
