# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_form1cat1_form1cat2_form1cat3_form1endterm_form2cat1_form2cat2_form2cat3_form2endterm_form3cat1_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStudyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip One')),
                ('tip1_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip One File')),
                ('tip2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Two')),
                ('tip2_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Two File')),
                ('tip3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Three')),
                ('tip3_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Three File')),
                ('tip4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Four')),
                ('tip4_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Four File')),
                ('tip5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Five')),
                ('tip5_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Five File')),
                ('tip6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Six')),
                ('tip6_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Six File')),
                ('tip7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Seven')),
                ('tip7_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Seven File')),
                ('tip8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eight')),
                ('tip8_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Eight File')),
                ('tip9', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Nine')),
                ('tip9_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Nine File')),
                ('tip10', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Ten')),
                ('tip10_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Ten File')),
                ('tip11', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eleven')),
                ('tip11_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Eleven File')),
                ('tip12', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Twelve')),
                ('tip12_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Twelve File')),
                ('tip13', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Thirteen')),
                ('tip13_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Thirteen File')),
                ('tip14', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fourteen')),
                ('tip14_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Fourteen File')),
                ('tip15', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fifteen')),
                ('tip15_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/basic', verbose_name='Tip Fifteen File')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumStudyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip One')),
                ('tip1_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip One File')),
                ('tip2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Two')),
                ('tip2_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Two File')),
                ('tip3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Three')),
                ('tip3_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Three File')),
                ('tip4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Four')),
                ('tip4_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Four File')),
                ('tip5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Five')),
                ('tip5_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Five File')),
                ('tip6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Six')),
                ('tip6_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Six File')),
                ('tip7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Seven')),
                ('tip7_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Seven File')),
                ('tip8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eight')),
                ('tip8_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Eight File')),
                ('tip9', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Nine')),
                ('tip9_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Nine File')),
                ('tip10', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Ten')),
                ('tip10_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Ten File')),
                ('tip11', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Eleven')),
                ('tip11_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Eleven File')),
                ('tip12', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Twelve')),
                ('tip12_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Twelve File')),
                ('tip13', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Thirteen')),
                ('tip13_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Thirteen File')),
                ('tip14', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fourteen')),
                ('tip14_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Fourteen File')),
                ('tip15', models.CharField(blank=True, max_length=200, null=True, verbose_name='Study Tip Fifteen')),
                ('tip15_file', models.FileField(blank=True, max_length=200, null=True, upload_to='membership/study_tips/premium', verbose_name='Tip Fifteen File')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyTip',
        ),
    ]
