# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_photo',
            field=models.ImageField(upload_to='college_photos'),
        ),
    ]
