# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20160119_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_photo',
        ),
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.AddField(
            model_name='college',
            name='college_logo',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 32, 5, 698215, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_motto',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 32, 17, 669384, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo1',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 32, 35, 90813, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo2',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 32, 46, 16772, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo3',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 32, 56, 319002, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo4',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 33, 8, 369421, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo5',
            field=models.ImageField(default=datetime.datetime(2016, 1, 20, 10, 33, 22, 668078, tzinfo=utc), upload_to='high_school/high_school_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='course_five',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='course_four',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='course_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='course_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='course_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 20, 10, 33, 32, 251554, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='featured',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 33, 42, 880753, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 34, 24, 121856, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 34, 34, 431194, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='po_box',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 10, 34, 44, 232210, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=500),
        ),
    ]
