# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20160120_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_logo',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_photo1',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_photo2',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_photo3',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_photo4',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_photo5',
            field=models.ImageField(upload_to='colleges/college_photos'),
        ),
    ]
