# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20160120_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_file',
            field=models.FileField(blank=True, upload_to='colleges/college_files'),
        ),
    ]
