# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading_six',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 8, 37, 53, 695025, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_six',
            field=models.ImageField(default=datetime.datetime(2016, 1, 14, 8, 38, 9, 657921, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_six',
            field=models.TextField(default=datetime.datetime(2016, 1, 14, 8, 38, 19, 783416, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
