# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20160114_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_one',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='article',
            name='question',
            field=models.TextField(default=datetime.datetime(2016, 1, 14, 8, 44, 47, 879241, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
