# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20151229_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.AddField(
            model_name='job',
            name='job_description1',
            field=models.TextField(default=datetime.datetime(2016, 1, 21, 0, 48, 51, 19103, tzinfo=utc), verbose_name='Paragraph_one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_description2',
            field=models.TextField(blank=True, verbose_name='Paragraph_one'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description3',
            field=models.TextField(blank=True, verbose_name='Paragraph_one'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description4',
            field=models.TextField(blank=True, verbose_name='Paragraph_one'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description5',
            field=models.TextField(blank=True, verbose_name='Paragraph_one'),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 21, 0, 49, 3, 416236, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
