# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160121_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description1',
            field=models.TextField(verbose_name='Paragraph One'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description2',
            field=models.TextField(blank=True, verbose_name='Paragraph Two(Optional)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description3',
            field=models.TextField(blank=True, verbose_name='Paragraph Three(Optional)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description4',
            field=models.TextField(blank=True, verbose_name='Paragraph Four(Optional)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description5',
            field=models.TextField(blank=True, verbose_name='Paragraph Five(Optional)'),
        ),
    ]
