# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160121_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 0, 55, 36, 616310, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
